### ISSUE TITLE
batch analysis errors

### ISSUE THREAD

**Issue by subhamoydas** [bioimage-analysis/julia_clusters#1]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/anaconda3/envs/name_env/lib/python3.7/site-packages/pandas/core/internals/managers.py in create_block_manager_from_blocks(blocks, axes)
   1650                 blocks = [make_block(values=blocks[0],
-> 1651                                      placement=slice(0, len(axes[0])))]
   1652 

/anaconda3/envs/name_env/lib/python3.7/site-packages/pandas/core/internals/blocks.py in make_block(values, placement, klass, ndim, dtype, fastpath)
   3094 
-> 3095     return klass(values, ndim=ndim, placement=placement)
   3096 

/anaconda3/envs/name_env/lib/python3.7/site-packages/pandas/core/internals/blocks.py in __init__(self, values, placement, ndim)
     86                 'Wrong number of items passed {val}, placement implies '
---> 87                 '{mgr}'.format(val=len(self.values), mgr=len(self.mgr_locs)))
     88 

ValueError: Wrong number of items passed 1, placement implies 2

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-5-8de19ae6b5e7> in <module>
----> 1 batch_analysis.batch_analysis(path, imageformat = '.lif')

~/julia_clusters/scripts/batch_analysis.py in batch_analysis(path, **kwargs)
     30                                                 directory, plot = False,save = True)
     31         del gauss
---> 32         analysis.create_dataframe(ganglion_prop, local_maxi, meta, directory, save = True)

~/julia_clusters/scripts/analysis.py in create_dataframe(ganglion_prop, local_maxi, meta, directory, save)
     21     orientation_gang = [prop.orientation for prop in ganglion_prop]
     22 
---> 23     df = pd.DataFrame(result, columns = ['ganglion', 'Nbr of neurons'])
     24     df["surface ganglion"] = surface_gang
     25     df["major axis length"] = major_gang

/anaconda3/envs/name_env/lib/python3.7/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    421             else:
    422                 mgr = init_ndarray(data, index, columns, dtype=dtype,
--> 423                                    copy=copy)
    424 
    425         # For data is list-like, or Iterable (will consume into list)

/anaconda3/envs/name_env/lib/python3.7/site-packages/pandas/core/internals/construction.py in init_ndarray(values, index, columns, dtype, copy)
    165         values = maybe_infer_to_datetimelike(values)
    166 
--> 167     return create_block_manager_from_blocks([values], [columns, index])
    168 
    169 

/anaconda3/envs/name_env/lib/python3.7/site-packages/pandas/core/internals/managers.py in create_block_manager_from_blocks(blocks, axes)
   1658         blocks = [getattr(b, 'values', b) for b in blocks]
   1659         tot_items = sum(b.shape[0] for b in blocks)
-> 1660         construction_error(tot_items, blocks[0].shape[1:], axes, e)
   1661 
   1662 

/anaconda3/envs/name_env/lib/python3.7/site-packages/pandas/core/internals/managers.py in construction_error(tot_items, block_shape, axes, e)
   1687         raise e
   1688     if block_shape[0] == 0:
-> 1689         raise ValueError("Empty data passed with indices specified.")
   1690     raise ValueError("Shape of passed values is {0}, indices imply {1}".format(
   1691         passed, implied))

ValueError: Empty data passed with indices specified.

**Comment by bioimage-analysis** [comment]
Hi Moy, thank you, I have adjusted it so if there is no ganglion in the image it should still work, just give an empty dataframe
